#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
import os
import pandas as pd
import re

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/download_and_make_ubam.smk"
include: "rules/align_star.smk"
include: "rules/sort_cram.smk"
include: "rules/telescope.smk"
include: "rules/stringtie.smk"

localrules: sample_download
rule sample_download:
    input:
        expand("results/ubam/{sample_id}.bam", sample_id=list(samples.index))

## when job completed, remove the ubam to save space
localrules: star_align
rule star_align:
    input:
        "results/align_multi/{sample_id}/Aligned.out.bam",
        "results/align_multi/{sample_id}/ReadsPerGene.out.tab",
        "results/align_multi/{sample_id}/Aligned.sortedByCoord.out.cram",
        "results/ubam/{sample_id}.bam",
    output:
        touch("results/complete/{sample_id}_star_align.txt")
    shell:
        '''
rm {input[3]}
        '''               

localrules: star_complete
rule star_complete:
    input:
        expand("results/complete/{s}_star_align.txt", s=list(samples.index))

localrules: sample_complete
rule sample_complete:
    input:
        "results/align_multi/{sample_id}/Aligned.sortedByCoord.out.bam",
        "results/align_multi/{sample_id}/Aligned.out.bam",
        rules.telescope.output,
        rules.stringtie.output
    output:
        touch("results/complete/{sample_id}.txt")
    shell:
        '''
rm {input[0]}
rm {input[1]}
        '''      

localrules: all
rule all:
    input:
        expand("results/complete/{s}.txt", s=list(samples.index))
